services:
  url-tracker:
    build:
      context: ..
      dockerfile: app/url-tracker.dockerfile
    container_name: url-tracker
    user: "1002:1002"
    volumes:
      - ../config.yml:/app/config.yml:ro
      - ../data/:/app/data
      - ../logs:/app/logs
    restart: unless-stopped
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - proxy

networks:
  proxy:
    external: true
